name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'assets/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'assets/**'
      - '.github/workflows/build.yml'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build tests
      run: make test

    - name: Run tests
      run: ./bin/test_runner

    # Doesn't upload artifacts, as they are unsigned
    - name: Build workflow
      run: make package
