name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build tests
      run: make test

    - name: Run tests
      run: ./bin/test_runner

    - name: Build workflow
      run: make package

    - name: Archive workflow
      uses: actions/upload-artifact@v4
      with:
        path: suspicious-number.alfredworkflow
