name: Build

on:
  push:
    branches:
      - main
      - workflow-test
    paths:
      - 'src/**'
      - 'assets/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'assets/**'
      - '.github/workflows/build.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build tests
      run: make test

    - name: Run tests
      run: ./bin/test_runner

    - name: Build workflow
      run: make package

    - name: Archive workflow
      uses: actions/upload-artifact@v4
      with:
        path: suspicious-number.alfredworkflow
